# Generated by Django 4.0.5 on 2022-06-25 07:51

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('I', 'Interviewer'), ('C', 'Candidate')], default='I', max_length=1)),
                ('available_on', models.DateField(default=datetime.date.today)),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
